#!/usr/bin/env bash

# Exit immediately upon error.
set -e

sudo apt-get update
sudo apt-get install -y build-essential python3-dev
sudo apt-get install -y python3-pip

# This Ansible version should always be in-sync with the version of Ansible tracked by Poetry.
python3 -m pip install --user 'ansible==2.10.4'
