---

# Slightly future proofing this (shrug).
- name: Check if Raspberry Pi-Based OS
  ansible.builtin.stat:
    path: /boot/config.txt
  register: rpi

- ansible.builtin.import_tasks: uart.yml
  when: rpi.stat.exists and uart.enabled | bool
