---

- name: Enable Mini UART on GPIO pins 14 (Tx) and 15 (Rx)
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    line: enable_uart=1
  when: uart.type == 'mini'

# This switches the PL011 UART from the bluetooth controller to GPIO pins 14 (Tx) and 15
# (Rx), which disables bluetooth on the board.
- name: Enable PL011 UART on GPIO pins 14 (Tx) and 15 (Rx)
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    line: btoverlay=disable-bt
  notify: Disable Bluetooth Modems
  when: uart.type == 'PL011'
